languagem: java
jdk: "-openjdk8"
deploy:
  provider: heroku
  api_key:
    secure: DwdTzfosti619iexqbASVsK/B3HvgmyXWytKeNSo4IcxRqp8kPuHh0r4rSzCxq4KH7qvv+yF0pZKvIDYx/U9E9I1wj3mPrKkKIs/BHVqkU98UH9GOHEBntS1CG/kWfczukGgP8/vjtUt5qKKQqzLbUIYF/4TE/ZJR2tbHfBkcKy4L+gtKOX7aa4MRLimEGXzzGuHqRAVysJ4AStwNUhn04Og3TxCY8V/bWNMfXF+w48cUWA3FatfVDfK9LpC00BHh7Dnjeb+lH4+zBJrtQ2SHU7Fto7+V4rFlnmMMQM9lytDjxfi7jyeKKrOGB3N2BjD2aBgIcfyc/7Vn1TZ20Agxy14F8VQ/h885xFb+AvQEJuPhDTnXCsctnISUEh8t5+LUx84W5CKkUE1HHCElNhI4ONUjQbqfDL3hjsEk5UYZNoize2g6H7N6LsMKZPi1csOtBGE1iWYaKFdN9h/amnzaLpZZU8QfZNnLXjgxOxQMU5eUyN52dbfFpC/NavwECk0dWOLjiIKAF0w36DIO/6aNROhWJuYovKqYV3RAx0TRr9+vv4kTBevpullOLwAUMpFZw6mrbUSOOlrm5NrGiAOFwXyunSzPudAZLqkopTIeQrcMSnRivYTx05RM37KAZ4HUgceoqDXT+k0ubRBfjCbqtJi39HHb9uO4a3NZ9+ZBGw=
  app: ms-grade-curricular-dev
  on:
    all_branches: true
